<template>
  <div class="quetionBeginPage">
    <h1 @click="beginAnswer" v-if="showSelect">开始测试</h1>
    <span v-else class="flip-scale-down-ver" style="font-size: 200px; color: rgb(208, 107, 107)">{{ time }}</span>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
const Router = useRouter()
let time = ref(3)
let timer
let showSelect = ref(true)

watch(time, (value) => {
  if (value === 0) {
    Router.replace({
      path: '/mmse/questions'
    })
    clearInterval(timer)
  }
})
const beginAnswer = () => {
  showSelect.value = !showSelect.value
  timer = setInterval(() => {
    time.value--
  }, 1000)
}
</script>

<style lang="scss" scoped>
.quetionBeginPage {
  width: 100%;
  height: calc(100% - 50px);
  background-color: rgb(234, 245, 247);
  display: flex;
  align-items: center;
  justify-content: center;

  h1 {
    margin: 0;
    text-align: center;

    font-size: 5em;
    transition: 0.5s;
    font-family: Arial, Helvetica, sans-serif;
    cursor: pointer;
  }

  h1:hover {
    text-shadow:
      0 1px 0 #ccc,
      0 2px 0 #ccc,
      0 3px 0 #ccc,
      0 4px 0 #ccc,
      0 5px 0 #ccc,
      0 6px 0 #ccc,
      0 7px 0 #ccc,
      0 8px 0 #ccc,
      0 9px 0 #ccc,
      0 10px 0 #ccc,
      0 11px 0 #ccc,
      0 12px 0 #ccc,
      0 20px 30px rgba(0, 0, 0, 0.5);
  }
  .flip-scale-down-ver {
    -webkit-animation: flip-scale-down-ver 1s linear 3 both;
    animation: flip-scale-down-ver 1s linear 3 both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2024-1-23 19:54:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation flip-scale-down-ver
 * ----------------------------------------
 */
  @-webkit-keyframes flip-scale-down-ver {
    0% {
      -webkit-transform: scale(1) rotateY(0);
      transform: scale(1) rotateY(0);
    }
    50% {
      -webkit-transform: scale(0.4) rotateY(-90deg);
      transform: scale(0.4) rotateY(-90deg);
    }
    100% {
      -webkit-transform: scale(1) rotateY(-180deg);
      transform: scale(1) rotateY(-180deg);
    }
  }
  @keyframes flip-scale-down-ver {
    0% {
      -webkit-transform: scale(1) rotateY(0);
      transform: scale(1) rotateY(0);
    }
    50% {
      -webkit-transform: scale(0.4) rotateY(-90deg);
      transform: scale(0.4) rotateY(-90deg);
    }
    100% {
      -webkit-transform: scale(1) rotateY(-180deg);
      transform: scale(1) rotateY(-180deg);
    }
  }
}
</style>
