# Generated by Django 3.2.18 on 2023-12-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('authority', models.IntegerField(default=0, verbose_name='权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_user',
                'ordering': ['id'],
            },
        ),
    ]
