# Generated by Django 3.2.18 on 2023-12-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, null=True, verbose_name='描述')),
                ('collection', models.BooleanField(default=False, verbose_name='是否查看')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            options={
                'verbose_name': '反馈信息表',
                'verbose_name_plural': '反馈信息表',
                'db_table': 't_feedback',
                'ordering': ['id'],
            },
        ),
    ]
