# Generated by Django 3.2.18 on 2023-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_feedbackinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('query_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_text', models.TextField()),
                ('response_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '日志表',
                'verbose_name_plural': '日志表',
                'db_table': 't_log',
                'ordering': ['id'],
            },
        ),
    ]
